permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 5
comments: false
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: 

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Beg for Mercy
title: Beg for Mercy
description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
# meta_keywords: "site, website, loja virtual, lojas virtuais, e-commerce, wordpress, frontend, front-end, html5, css3, javascript, jquery, seo, otimizacao, performance"
url: http://beg-for-mercy.github.io
production_url: http://beg-for-mercy.github.io
# repo: https://github.com/nandomoreirame/nandomoreira-jekyll-theme
#disqus_shortname: "nandothemes"
rss_path: source/
author:
#   name      : Fernando Moreira
  image     : /assets/images/author.jpg
#   email     :
#   url       :
#   facebook  :
#   twitter   :
#   instagram :
  github    : https://github.com/beg-for-mercy/beg-for-mercy.github.io
#   linkedin  :
#   bio       :

# thought
# thought:
#   text: I have no special talent. I am only passionately curious.
#   author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
